DELETE FROM mysql.user;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'finger' with GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'node'@'%';

FLUSH PRIVILEGES;
DROP DATABASE IF EXISTS test;
